//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod auth_permission;
pub mod auth_role;
pub mod auth_role_permission;
pub mod auth_user;
pub mod auth_user_role;
pub mod subject_brief;
pub mod subject_category;
pub mod subject_info;
pub mod subject_judge;
pub mod subject_label;
pub mod subject_mapping;
pub mod subject_multiple;
pub mod subject_radio;
