//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::auth_permission::Entity as AuthPermission;
pub use super::auth_role::Entity as AuthRole;
pub use super::auth_role_permission::Entity as AuthRolePermission;
pub use super::auth_user::Entity as AuthUser;
pub use super::auth_user_role::Entity as AuthUserRole;
pub use super::subject_brief::Entity as SubjectBrief;
pub use super::subject_category::Entity as SubjectCategory;
pub use super::subject_info::Entity as SubjectInfo;
pub use super::subject_judge::Entity as SubjectJudge;
pub use super::subject_label::Entity as SubjectLabel;
pub use super::subject_mapping::Entity as SubjectMapping;
pub use super::subject_multiple::Entity as SubjectMultiple;
pub use super::subject_radio::Entity as SubjectRadio;
