//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "subject_radio")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub subject_id: Option<i64>,
    pub option_type: Option<i8>,
    pub option_content: Option<String>,
    pub is_correct: Option<i8>,
    pub created_by: Option<String>,
    pub created_time: Option<DateTime>,
    pub update_by: Option<String>,
    pub update_time: Option<DateTime>,
    pub is_deleted: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
